# Generated by Django 2.2.4 on 2021-01-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_manage_app', '0004_auto_20210128_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
